# Generated by Django 4.2.3 on 2023-07-21 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumApp', '0002_subreddemcommunity_post_community'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubreddemCommunity',
            new_name='ReddemCommunity',
        ),
    ]
