# Generated by Django 4.2.3 on 2023-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_rename_subreddemcommunity_reddemcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddemcommunity',
            name='image',
            field=models.ImageField(default=False, upload_to='CommunityImages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reddemcommunity',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
