# Generated by Django 4.2.3 on 2023-07-23 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumApp', '0009_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddemcommunity',
            name='members',
            field=models.ManyToManyField(through='forumApp.UserJoinedCommunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reddemcommunity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
