# Generated by Django 4.2.3 on 2023-07-23 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumApp', '0010_reddemcommunity_members_alter_reddemcommunity_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserJoinedCommunities',
            new_name='ReddemCommunityMembers',
        ),
    ]
