# Generated by Django 4.2.3 on 2023-07-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumApp', '0011_rename_userjoinedcommunities_reddemcommunitymembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesAndDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField()),
                ('liked_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumApp.post')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
