# Generated by Django 4.2.3 on 2023-07-24 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0012_likesanddislikes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likesanddislikes',
            name='liked',
            field=models.BooleanField(),
        ),
    ]
