# Generated by Django 4.2.3 on 2023-08-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0014_votesanddownvotes_delete_likesanddislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reddemcommunity',
            options={'verbose_name_plural': 'Reddem communities'},
        ),
        migrations.AlterModelOptions(
            name='reddemcommunitymembers',
            options={'verbose_name_plural': 'Reddem community members'},
        ),
        migrations.AlterModelOptions(
            name='upvotesanddownvotesposts',
            options={'verbose_name_plural': 'Upvotes and downvotes posts'},
        ),
    ]
